### ISSUE TITLE
UpdateOrder()

### ISSUE THREAD

**Issue by developershivameena** [starweb/ongoing#2]
Fatal error: Uncaught SoapFault exception: [soap:Server] System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> System.NullReferenceException: Object reference not set to an instance of an object. at WMS.Interface.Engine.WebServiceLogon.GetUsersRow(String userName) at WMS.Interface.Engine.WebServiceLogon.LogonUserResult(String userName, String password, String goodsOwnerCode) at WMS.Interface.Service.UpdateOrder(String GoodsOwnerCode, String UserName, String Password, UpdateOrder updateOrder)

**Comment by felixsand** [comment]
@developershivameena Do you have any more information regarding this?
When does it occur?
